### ISSUE TITLE
[Bubble]  Custom money display

### ISSUE THREAD

**Issue by majaStamenkovic** [com-480-data-visualization/com-480-project-vizzybussy#13]

**Comment by Jmion** [comment]
Add million / billion text to chart

**Comment by Jmion** [comment]
![Screenshot 2020-05-20 at 15 06 18](https://user-images.githubusercontent.com/15061803/82449520-9f3ece80-9aab-11ea-8618-12250f20e440.png)

**Comment by Jmion** [comment]
@majaStamenkovic Does this seem like a good format for the revenue?
![Screenshot 2020-05-20 at 15 06 18](https://user-images.githubusercontent.com/15061803/82449576-baa9d980-9aab-11ea-8fdb-6c903221dd75.png)

Thanks :)

**Comment by majaStamenkovic** [comment]
Oui, c'est super
