### ISSUE TITLE
[All] change font

### ISSUE THREAD

**Issue by majaStamenkovic** [com-480-data-visualization/com-480-project-vizzybussy#18]

**Comment by Jmion** [comment]
We are using: Open Sans for a classic font.
You can use it by:
**include:** `<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">`
**css rule:** `font-family: 'Open Sans', sans-serif;`
The handwritten cool font: Indie Flower
**include:** ` <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">`
**css rule**: `font-family: 'Indie Flower', cursive;`

**Comment by majaStamenkovic** [comment]
Didn't we say that we are not using Indie Flower (because of the colors?)

**Comment by Jmion** [comment]
Ok we will talk about this during our meeting. I have only used open sans in my graph.

**Comment by majaStamenkovic** [comment]
Open Sans & Raleway
