### ISSUE TITLE
[Timeline] Card size

### ISSUE THREAD

**Issue by majaStamenkovic** [com-480-data-visualization/com-480-project-vizzybussy#29]

**Comment by Jmion** [comment]
Here is an idea. Make the text div where you are putting the text a fix height. Then when you fill it with text if there is an issue with the text being to long the div can simply scroll. Seems like that could solve the issue that can be seen here:
![image](https://user-images.githubusercontent.com/15061803/82649692-e6e36880-9c19-11ea-9e6a-c2c64478f60b.png)
